export const ENV = {
  PAYLOAD: 'PAYLOAD',
  JOB_ID: 'JOB_ID',
  SUPABASE_URL: 'SUPABASE_URL',
  SUPABASE_SERVICE_ROLE_KEY: 'SUPABASE_SERVICE_ROLE_KEY',
  PROJECTS_TABLE: 'PROJECTS_TABLE',
  ECS_CLUSTER: 'ECS_CLUSTER',
  ECS_TASK_DEFINITION: 'ECS_TASK_DEFINITION',
  ECS_SUBNETS: 'ECS_SUBNETS',
  ECS_SECURITY_GROUP: 'ECS_SECURITY_GROUP',
  BUILDS_BUCKET: 'BUILDS_BUCKET',
  CODEBUILD_PROJECT: 'CODEBUILD_PROJECT',
  PROJECT_KEY: 'PROJECT_KEY',
} as const;

export enum JobStatus {
  Pending = 'pending',
  Running = 'running',
  Completed = 'completed',
  Failed = 'failed',
}
